-- Seed syllabi for JEE and NEET.
-- Apply with:  turso db shell <your-db> < seed-jee-neet.sql
-- Safe to re-run; conflicts are ignored.

-- ===== JEE =====
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Physics', 'Mechanics', 'Kinematics in one and two dimensions');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Physics', 'Mechanics', 'Newton''s laws and friction');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Physics', 'Mechanics', 'Work, energy and power');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Physics', 'Mechanics', 'Centre of mass and collisions');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Physics', 'Mechanics', 'Rotational motion and moment of inertia');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Physics', 'Mechanics', 'Gravitation and orbits');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Physics', 'Mechanics', 'Fluid mechanics and surface tension');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Physics', 'Oscillations & Waves', 'Simple harmonic motion');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Physics', 'Oscillations & Waves', 'Waves, superposition and Doppler effect');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Physics', 'Thermal Physics', 'Thermodynamic processes and laws');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Physics', 'Thermal Physics', 'Kinetic theory of gases');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Physics', 'Electrodynamics', 'Electrostatics and Gauss''s law');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Physics', 'Electrodynamics', 'Capacitors');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Physics', 'Electrodynamics', 'Current electricity and circuits');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Physics', 'Electrodynamics', 'Magnetic effects of current');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Physics', 'Electrodynamics', 'Electromagnetic induction and AC');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Physics', 'Optics', 'Ray optics and optical instruments');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Physics', 'Optics', 'Wave optics: interference and diffraction');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Physics', 'Modern Physics', 'Photoelectric effect and dual nature');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Physics', 'Modern Physics', 'Atomic models and nuclei');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Physics', 'Modern Physics', 'Semiconductors and logic gates');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Chemistry', 'Physical', 'Mole concept and stoichiometry');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Chemistry', 'Physical', 'Atomic structure and quantum numbers');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Chemistry', 'Physical', 'Chemical thermodynamics');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Chemistry', 'Physical', 'Chemical and ionic equilibrium');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Chemistry', 'Physical', 'Redox reactions');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Chemistry', 'Physical', 'Electrochemistry');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Chemistry', 'Physical', 'Chemical kinetics');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Chemistry', 'Physical', 'Solutions and colligative properties');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Chemistry', 'Inorganic', 'Periodic table and periodicity');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Chemistry', 'Inorganic', 'Chemical bonding and molecular structure');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Chemistry', 'Inorganic', 's-block and p-block elements');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Chemistry', 'Inorganic', 'd- and f-block elements');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Chemistry', 'Inorganic', 'Coordination compounds');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Chemistry', 'Organic', 'General organic chemistry and isomerism');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Chemistry', 'Organic', 'Hydrocarbons');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Chemistry', 'Organic', 'Haloalkanes and haloarenes');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Chemistry', 'Organic', 'Alcohols, phenols and ethers');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Chemistry', 'Organic', 'Aldehydes, ketones and carboxylic acids');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Chemistry', 'Organic', 'Amines and diazonium salts');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Chemistry', 'Organic', 'Biomolecules and polymers');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Mathematics', 'Algebra', 'Quadratic equations and inequalities');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Mathematics', 'Algebra', 'Sequences and series');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Mathematics', 'Algebra', 'Complex numbers');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Mathematics', 'Algebra', 'Permutations and combinations');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Mathematics', 'Algebra', 'Binomial theorem');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Mathematics', 'Algebra', 'Matrices and determinants');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Mathematics', 'Trigonometry', 'Trigonometric identities and equations');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Mathematics', 'Trigonometry', 'Inverse trigonometric functions');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Mathematics', 'Coordinate Geometry', 'Straight lines and pair of lines');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Mathematics', 'Coordinate Geometry', 'Circles');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Mathematics', 'Coordinate Geometry', 'Parabola, ellipse and hyperbola');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Mathematics', 'Calculus', 'Limits, continuity and differentiability');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Mathematics', 'Calculus', 'Differentiation and applications');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Mathematics', 'Calculus', 'Indefinite integration');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Mathematics', 'Calculus', 'Definite integration and areas');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Mathematics', 'Calculus', 'Differential equations');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Mathematics', 'Vectors & 3D', 'Vector algebra');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Mathematics', 'Vectors & 3D', 'Three dimensional geometry');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Mathematics', 'Probability', 'Probability and Bayes theorem');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('jee', 'Mathematics', 'Probability', 'Statistics');

-- ===== NEET =====
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Physics', 'Mechanics', 'Kinematics and motion in a plane');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Physics', 'Mechanics', 'Laws of motion and friction');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Physics', 'Mechanics', 'Work, energy and power');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Physics', 'Mechanics', 'Rotational motion');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Physics', 'Mechanics', 'Gravitation');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Physics', 'Properties of Matter', 'Elasticity, fluids and surface tension');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Physics', 'Thermal Physics', 'Thermodynamics');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Physics', 'Thermal Physics', 'Kinetic theory of gases');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Physics', 'Oscillations & Waves', 'Oscillations and waves');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Physics', 'Electrodynamics', 'Electrostatics and capacitance');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Physics', 'Electrodynamics', 'Current electricity');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Physics', 'Electrodynamics', 'Magnetism and magnetic effects of current');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Physics', 'Electrodynamics', 'EMI and alternating current');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Physics', 'Optics', 'Ray and wave optics');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Physics', 'Modern Physics', 'Dual nature of matter and radiation');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Physics', 'Modern Physics', 'Atoms, nuclei and semiconductors');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Chemistry', 'Physical', 'Some basic concepts and mole concept');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Chemistry', 'Physical', 'Structure of atom');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Chemistry', 'Physical', 'Thermodynamics and thermochemistry');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Chemistry', 'Physical', 'Equilibrium');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Chemistry', 'Physical', 'Redox reactions and electrochemistry');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Chemistry', 'Physical', 'Chemical kinetics');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Chemistry', 'Physical', 'Solutions');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Chemistry', 'Inorganic', 'Classification of elements and periodicity');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Chemistry', 'Inorganic', 'Chemical bonding');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Chemistry', 'Inorganic', 'p-block elements');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Chemistry', 'Inorganic', 'd- and f-block elements');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Chemistry', 'Inorganic', 'Coordination compounds');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Chemistry', 'Organic', 'Basic principles of organic chemistry');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Chemistry', 'Organic', 'Hydrocarbons');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Chemistry', 'Organic', 'Haloalkanes, alcohols, phenols and ethers');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Chemistry', 'Organic', 'Aldehydes, ketones, carboxylic acids and amines');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Chemistry', 'Organic', 'Biomolecules');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Biology', 'Diversity of Life', 'Living world and biological classification');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Biology', 'Diversity of Life', 'Plant kingdom and animal kingdom');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Biology', 'Structural Organisation', 'Morphology and anatomy of flowering plants');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Biology', 'Structural Organisation', 'Structural organisation in animals');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Biology', 'Cell Biology', 'Cell: the unit of life');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Biology', 'Cell Biology', 'Biomolecules');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Biology', 'Cell Biology', 'Cell cycle and cell division');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Biology', 'Plant Physiology', 'Transport and mineral nutrition in plants');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Biology', 'Plant Physiology', 'Photosynthesis in higher plants');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Biology', 'Plant Physiology', 'Respiration in plants and plant growth');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Biology', 'Human Physiology', 'Digestion and absorption');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Biology', 'Human Physiology', 'Breathing and exchange of gases');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Biology', 'Human Physiology', 'Body fluids and circulation');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Biology', 'Human Physiology', 'Excretory products and elimination');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Biology', 'Human Physiology', 'Locomotion and movement');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Biology', 'Human Physiology', 'Neural control and coordination');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Biology', 'Human Physiology', 'Chemical coordination and integration');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Biology', 'Reproduction', 'Sexual reproduction in flowering plants');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Biology', 'Reproduction', 'Human reproduction and reproductive health');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Biology', 'Genetics & Evolution', 'Principles of inheritance and variation');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Biology', 'Genetics & Evolution', 'Molecular basis of inheritance');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Biology', 'Genetics & Evolution', 'Evolution');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Biology', 'Biology & Human Welfare', 'Human health and disease');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Biology', 'Biology & Human Welfare', 'Microbes in human welfare');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Biology', 'Biotechnology', 'Biotechnology principles and processes');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Biology', 'Biotechnology', 'Biotechnology and its applications');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Biology', 'Ecology', 'Organisms, populations and ecosystem');
INSERT OR IGNORE INTO syllabus (mode, subject, unit, topic) VALUES ('neet', 'Biology', 'Ecology', 'Biodiversity and conservation');

